// Generated by CoffeeScript 1.9.3
var API;

API = new FacadeAPI('ws://localhost:8090', function() {
  var Chat, rendered;
  API.addListener('error', function(data) {
    return alert(data.error_descr);
  });
  API.addListener('join', function(data) {
    return rendered.setActive(1);
  });
  API.addListener('auth_success', function(data) {
    alert("Успешно вошли как " + data.nickname);
    rendered.forceUpdate();
    return rendered.setActive(1);
  });
  Chat = React.createClass({
    setActive: function(num) {
      return this.setState({
        tab: num
      });
    },
    getInitialState: function() {
      return {
        tab: 1
      };
    },
    getElement: function(num) {
      switch (num) {
        case 1:
          return React.createElement(MainChat, null);
        case 2:
          return React.createElement(Rooms, null);
        case 3:
          return React.createElement(Orders, null);
        case 4:
          return React.createElement(Auth, null);
      }
    },
    render: function() {
      return React.createElement("div", {
        "className": 'container'
      }, React.createElement(Menu, {
        "tab": this.state.tab
      }), this.getElement(this.state.tab));
    }
  });
  return rendered = React.render(React.createElement(Chat, null), document.getElementById('chat'), function() {
    return document.getElementById('buttons').onclick = function(e) {
      var number;
      number = e.target.getAttribute('data-num');
      if (number) {
        rendered.setActive(+number);
      }
      return false;
      return e.preventDefault();
    };
  });
});
